config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
  	resources :comments
  end
  resources :tags

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	

	def tag_list
	  tags.join(", ")
	end

	def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

 	def tag_list=(tags_string)
 		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
 		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
 		self.tags = new_or_found_tags
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
  		@article = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
  		@article.save

  		flash.notice = "Article '#{@article.title}' Created!"


  		redirect_to article_path(@article)
	end
	
	def article_params
    	params.require(:article).permit(:title, :body, :tag_list)
  	end

	def destroy
		  @article = Article.find(params[:id])
		  @article.destroy

		  flash.notice = "Article '#{@article.title}' Destroyed!"

		  redirect_to article_path(@article)
	 end

  	def edit
  		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' Updated!"


		redirect_to article_path(@article)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @article.each do |article| %>
    <li>
	<%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
	<%= link_to "Create a New Article", new_article_path, class: "new_article"%>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
	
	<p>
	  Tags:
	  <% @article.tags.each do |tag| %>
	    <%= link_to tag.name, tag_path(tag) %>
	  <% end %>
	</p>
	
	<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
<%= link_to "edit", edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<p class="flash"><%= flash.notice %></p>
	<%= yield %>

</body>
</html>